server:
  port: ${ADMIN_SERVER_PORT:8080}
spring:
  application:
    name: ${ADMIN_APPLICATION_NAME:zza-rental-admin}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${ADMIN_DB_URL}
    username: ${ADMIN_DB_USERNAME}
    password: ${ADMIN_DB_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: ${ADMIN_DB_CONNECTION_TIMEOUT_MS:60000}
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: ${ADMIN_DB_MAX_POOL_SIZE:12}
      minimum-idle: ${ADMIN_DB_MIN_IDLE:10}
      pool-name: SPHHikariPool
  jackson:
    time-zone: GMT+8
  data:
    redis:
      host: ${ADMIN_REDIS_HOST}
      port: ${ADMIN_REDIS_PORT:6379}
      database: ${ADMIN_REDIS_DATABASE:0}
      password: ${ADMIN_REDIS_PASSWORD}

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: ${ADMIN_MINIO_ENDPOINT}
  access-key: ${ADMIN_MINIO_ACCESS_KEY}
  secret-key: ${ADMIN_MINIO_SECRET_KEY}
  bucket-name: ${ADMIN_MINIO_BUCKET_NAME}

security:
  jwt:
    secret: ${ADMIN_JWT_SECRET}

springdoc:
  default-flat-param-object: true
