server:
  port: ${APP_SERVER_PORT:8081}
spring:
  application:
    name: ${APP_APPLICATION_NAME:zza-rental-app}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: ${APP_DB_CONNECTION_TIMEOUT_MS:60000}
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: ${APP_DB_MAX_POOL_SIZE:12}
      minimum-idle: ${APP_DB_MIN_IDLE:10}
      pool-name: SPHHikariPool
  jackson:
    time-zone: GMT+8
  data:
    redis:
      host: ${APP_REDIS_HOST}
      port: ${APP_REDIS_PORT:6379}
      database: ${APP_REDIS_DATABASE:0}
      password: ${APP_REDIS_PASSWORD}

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: ${APP_MINIO_ENDPOINT}
  access-key: ${APP_MINIO_ACCESS_KEY}
  secret-key: ${APP_MINIO_SECRET_KEY}
  bucket-name: ${APP_MINIO_BUCKET_NAME}

security:
  jwt:
    secret: ${APP_JWT_SECRET}

integration:
  sms:
    access-key-id: ${APP_SMS_ACCESS_KEY_ID}
    access-key-secret: ${APP_SMS_ACCESS_KEY_SECRET}
    endpoint: ${APP_SMS_ENDPOINT}
    sign-name: ${APP_SMS_SIGN_NAME}
    template-code: ${APP_SMS_TEMPLATE_CODE}
    connect-timeout-ms: "${APP_SMS_CONNECT_TIMEOUT_MS:}"
    read-timeout-ms: "${APP_SMS_READ_TIMEOUT_MS:}"

springdoc:
  default-flat-param-object: true

rocketmq:
  name-server: ${APP_ROCKETMQ_NAME_SERVER}
  producer:
    group: ${APP_ROCKETMQ_PRODUCER_GROUP}
